import { Center } from "@chakra-ui/react"
import Head from "next/head"
import { useState } from "react"
import Confetti from "react-confetti"
import useSound from "use-sound"

export default function Home() {
  const [shouldRenderConfetti, setRenderConfetti] = useState(false)
  const [play] = useSound("/partyhorn.mp3")

  const clicky = () => {
    setRenderConfetti(true)
    window.setTimeout(() => setRenderConfetti(false), 5000)
    play()
  }

  return (
    <>
      <Head>
        <title>{"GWEN'S PONYYYYY"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {shouldRenderConfetti && <Confetti />}

      <audio id="myTune">
        <source src="partyhorn.mp3"></source>
      </audio>

      <Center h={"100vh"}>
        <img src="/pony.png" alt={"It's a pony!"} onClick={clicky} />
      </Center>
    </>
  )
}
