import { Center } from "@chakra-ui/react"
import { Inter } from "next/font/google"
import Head from "next/head"
import { useRef, useState } from "react"
import Confetti from "react-confetti"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const [shouldRenderConfetti, setRenderConfetti] = useState(false)
  const [audio, setAudio] = useState(new Audio("/partyhorn.mp3"))
  const audioRef = useRef()

  const clicky = () => {
    console.log("heyooooo")
    setRenderConfetti(true)
    window.setTimeout(() => setRenderConfetti(false), 5000)
    audio.play()
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {shouldRenderConfetti && <Confetti />}

      <audio id="myTune">
        <source src="partyhorn.mp3"></source>
      </audio>

      <Center h={"100vh"}>
        <img src="/pony.png" alt="It's a pony!" onClick={clicky} />
      </Center>
    </>
  )
}
